### ISSUE TITLE
with_fileglob doesn't work without full path

### ISSUE THREAD

**Issue by lunarthegrey** [nginxinc/ansible-role-nginx#123]
I've noticed an issue where if you have any of the `*-upload_enable` vars set to `true` it skips the files and doesn't upload them when it contains regex.

For example:

```
nginx_http_upload_enable: true
nginx_http_upload_src: conf/http/*.conf
nginx_http_upload_dest: /etc/nginx/conf.d/
```

When I run the playbook with `-vvv` it shows

```
TASK [nginxinc.nginx : (Setup: All NGINX) Upload NGINX HTTP Configuration Files] ***********************************************************************************************
task path: /home/user/.ansible/roles/nginxinc.nginx/tasks/conf/upload-config.yml:16
Read vars_file 'vars/nginx.yml'
```

Even though there is a .conf file in that directory. When I specify the full path rather than the relative path it works. Example:

`conf/http/*.conf` vs `/home/user/ansible/ansible-nginx/conf/http/*.conf`

So it seems there's an issue.. I read in a few places that something like `conf/http/*.conf` would actually work if you ran your playbook from the Ansible role's directory, but have not tested it. Any ideas on how to fix this?

**Comment by alessfg** [comment]
Hi @lunarthegrey!

Sorry for the late reply! I've been trying to replicate your issue but everything seems to be working on my end. 

From what I can see, you are installing the role from Ansible Galaxy. If that is the case, and you wish to use `nginx_http_upload_src: conf/http/*.conf` you will have to include the files in `/home/user/.ansible/roles/nginxinc.nginx/files/conf/http`. By default, if you only provide a file name (eg `conf/http/*.conf` vs ./conf/http/*.conf`) the `copy` module looks for files located in the role `files` directory.

Alternatively, you can use a full path (as you've already discovered), or set a relative path (`../*.conf`) -- in the latter case Ansible will try to find the files at a location relative to the location of the Ansible playbook being deployed (not the role install location).

Let me know if that helps!

Cheers,
Alessandro.

**Comment by lunarthegrey** [comment]
Hello @alessfg!

That makes complete sense now. Since tasks are being run from the role's directory. I didn't think of that! Thank you for your help! Since this isn't really the bug/issue I thought it was I'll close this out now.

**Comment by alister** [comment]
I've just spent more than an hour trying to find the correct configuration to have files uploaded by this role (in my case, SSL certificates & keys).

For the next person - I offer this advice. If you don't want to have to put your files in the middle of someone else's role, and have your files more closely located to where you are running the role from - like such:

    # [your-role]/tasks/main.yml
	- include_role:
	    name: nginxinc.nginx
	  vars:
	    nginx_http_template_enable: false
    # [your-role]/files/[something]/certificate.crt

with an upload_src configuration like `nginx_ssl_crt_upload_src: ./ssl_certs/*.crt`, then DO NOT put the files to upload into `[your-role]/files/ssl/` - as the 'ssl' directory is already in the nginxinc.nginx role files/ directory (along with conf/, license/, & www/). If you use the same directory name as is already in this role will have Ansible stop looking when it finds the otherwise empty directory.

If, on the other hand, you create a directory such as `[your-role]/files/ssl_certs/` (or any other directory name that isn't used in the nginxinc.nginx's files/ directory) for your (hopefully encrypted *.crt/*.pem and *.key files) then Ansible will be able to find and upload your files from that directory.

They can then be configured as:

    nginx_ssl_crt_upload_src:  ./ssl_certs/*.crt  # or *.pem
