### ISSUE TITLE
Failed with ansible 2.8 on Centos7

### ISSUE THREAD

**Issue by dzmitry-rudnouski** [nginxinc/ansible-role-nginx#219]
**Describe the bug**
Role failed with ansible 2.8 on Centos7:
`{"changed": false, "msg": "No package matching 'nginx' found available, installed or updated", "rc": 126, "results": ["No package matching 'nginx' found available, installed or updated"]}`

With ansible 2.9 works fine.

Successfull ansible 2.9 run: 
https://travis-ci.org/lean-delivery/ansible-role-sonarqube/builds/642859374?utm_source=github_status&utm_medium=notification

Failed ansible 2.8 run: 
https://travis-ci.org/lean-delivery/ansible-role-sonarqube/builds/642866416?utm_source=github_status&utm_medium=notification

I guess this happens because of disablerepo, enablerepo mix here:
https://github.com/nginxinc/ansible-role-nginx/blob/master/tasks/opensource/setup-redhat.yml#L29
that doesn't work correctly in ansible 2.8, but works in ansible 2.9.

So you need either change min ansible version to 2.9 or try to remove disablerepo option - I suppose enablerepo is enough here.

**Comment by alessfg** [comment]
It will also fail with Ansible 2.9.3. It's a known issue with `disablerepo` and `enablerepo`. A fix has already been merged (https://github.com/ansible/ansible/pull/66557) and it will be available in the next release.

`disablerepo` is required for CentOS/RHEL 8 so I don't really want to touch it unless there's a better way to install NGINX that works for all the `yum` family releases. And, as of right now, changing the minimum Ansible version won't really fix anything either since the bug also affects the latest 2.9 release. 

My best advise for now is to not upgrade to the latest releases of Ansible, and once 2.10 (with the bug fix) is out I will set 2.10 as the minimum version. I can maybe add a temporary note to the README warning about the issue for the time being too.

**Comment by dzmitry-rudnouski** [comment]
Works good in 2.9.4.

**Comment by alessfg** [comment]
Welp, I somehow missed that they had pushed the bugfix to 2.9.4. I'll update the min required version.
