### ISSUE TITLE
incorrect repo for AWS ami

### ISSUE THREAD

**Issue by valugi** [nginxinc/ansible-role-nginx#229]
**Describe the bug**
Trying to install nginx on an AWS ami 
**To reproduce**
1. Deploy NGINX role using playbook.yml
2. Installs the centos/redhat repo
3. See errors

```
TASK [nginx : (Install: CentOS/RedHat) Install NGINX] ***************************************************************************************************************************************************************************************
fatal: [xx.xxx.xxx.xxx]: FAILED! => {"changed": false, "msg": "Failure talking to yum: failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.\nhttps://nginx.org/packages/mainline/centos/NA/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found"}
```

Yum update error

> failure: repodata/repomd.xml from nginx: [Errno 256] No more mirrors to try.
> https://nginx.org/packages/mainline/centos/NA/x86_64/repodata/repomd.xml: [Errno 14] HTTPS Error 404 - Not Found
> 

**Expected behavior**
To install nginx

**Your environment:**
 - Version of the NGINX Role or specific commit
latest
 - Version of Ansible
_ansible 2.7.9_

 - Target deployment platform
AMI flavour
```
$ cat /etc/os-release 
NAME="Amazon Linux AMI"
VERSION="2018.03"
ID="amzn"
ID_LIKE="rhel fedora"
VERSION_ID="2018.03"
PRETTY_NAME="Amazon Linux AMI 2018.03"
ANSI_COLOR="0;33"
CPE_NAME="cpe:/o:amazon:linux:2018.03:ga"
HOME_URL="http://aws.amazon.com/amazon-linux-ami/"
```

```
$ cat /etc/yum.repos.d/nginx.repo 
[nginx]
baseurl = https://nginx.org/packages/mainline/centos/NA/$basearch/
enabled = 1
gpgcheck = 1
name = NGINX Repository
```

Probably the path should have 7 instead of NA, maybe the CENTOS version is not detected properly.

I see that that supported OS for opensource version do not include AWS AMI linux, only the Nginx Plus - this could be the issue.

**Comment by valugi** [comment]
Did some introspection and AWS AMI returns `{{ ansible_distribution_major_version }}` as `"Centos Version NA"`

**Comment by alessfg** [comment]
Hiya @valugi, as you initially uncovered, the main issue here is that there's no supported build for NGINX Open Source on Amazon Linux, only NGINX Plus has builds for Amazon Linux (both 1 and 2).

**Comment by valugi** [comment]
is there a workaround?

**Comment by alessfg** [comment]
There might be some workarounds but sadly I do not know about them, nor is it recommended to try to install NGINX Open Source on Amazon Linux. I have never tried to use geerlingguy's role in Amazon Linux, does it work?

**Comment by valugi** [comment]
hi @alessfg ,
Yes it works, but he recommends now using this role.
https://github.com/geerlingguy/ansible-role-nginx

**Comment by magicalyak** [comment]
Not to drag this out too much but Amazon Linux isn't the same as Centos or Ubuntu.
AWS doesn't tell us much with it's Linux and the source or code, so it's really a guessing game.  That said, the centos rpms usually work just fine pinned to the kernel version.  I highly recommend using Centos but that's just my personal opinion.
I don't mean this disrespectfully but feel free to add this if you can test and prove it.  I'm not sure @alessfg will add it but if you get enough people saying this is a must-have I'm sure the community will listen.
If you can list out the manual steps, that would be a start.
To get this merged, more people need to say it's a must have.  The other place to push is Amazon themselves to submit a PR since they know the OS perfectly.

**Comment by valugi** [comment]
> There might be some workarounds but sadly I do not know about them, nor is it recommended to try to install NGINX Open Source on Amazon Linux. 

Any special reason for which is not recommended for open source version but recommended for Nginx plus?

I am trying to install a reverse proxy, and the AWS AMI is a stripped down version of Centos 7, in my opinion a good fit for the job.

**Comment by alessfg** [comment]
I've had a look at geerlinguy's role and he basically has the same repo file as this role has (https://github.com/geerlingguy/ansible-role-nginx/blob/master/templates/nginx.repo.j2#L3). You'll run into the same issue if you use his role on Amazon Linux.

My best and most honest recommendation would be to use a different distro if you want to run NGINX Open Source. Otherwise, as I mentioned, there might be some workarounds (tbd), but I can't add them to this role seeing how in the end Amazon Linux is not a supported platform.

**Comment by magicalyak** [comment]
As a really bad workaround for now, if you can get the rpm and store it local, you could just change the location to the local file.  I know that sounds horrible but that ansible variable should come back with 7Server not NA in most cases.  If the 7Server RPM works we may able to force that for Amazon Linux but likely needs a disclaimer that it's experimental.  
1) Need a variable to indicate what RPM to use matching Red Hat (this is a problem with the Amazon linux side)
2) if 7 works, maybe we could look at a local rpm option override?

**Comment by valugi** [comment]
The template is similar, but probably the default are covering the case when the Centos version is not detected. It works out of the box. 

@alessfg  I still do not understand why the Plus version is supported and OpenSource one is not, they come from the same repo no?

@magicalyak  I think I am part of the community - the part that is voicing the opinion. I am glad that Nginx is offering a role themselves and I want to take the advice of the guy who wrote a book about Ansible playbooks (geerlingguy) and use this role instead of his, but it should do at least what his role is doing for starters.

**Comment by valugi** [comment]
> As a really bad workaround for now, if you can get the rpm and store it local, you could just change the location to the local file. I know that sounds horrible but that ansible variable should come back with 7Server not NA in most cases. If the 7Server RPM works we may able to force that for Amazon Linux but likely needs a disclaimer that it's experimental.
> 
>     1. Need a variable to indicate what RPM to use matching Red Hat (this is a problem with the Amazon linux side)
> 
>     2. if 7 works, maybe we could look at a local rpm option override?

My workaround would be simpler and less intrusive, I would set the default version to 7 in case of Centos.

**Comment by magicalyak** [comment]
Feel free to submit it or fork and add this or just add locally.

I'd suggest pre_tasks
This will break when Amazon Linux goes with 8Server though.

pre_tasks:
- set_fact: ansible_distribution_major_version=7
  when: ansible_distribution == "Amazon" and ansible_distribution_major_version == "NA"

This is an issue with Amazon Linux not reporting it's server version because it's not open sourced, they just use dates.  If they add a way to be compatible with centos (which is where the upstream for Amazon Linux is obviously coming from) then we can use that.  Otherwise I'd use an override similar to below.

It is more fully explained here: https://mamchenkov.net/wordpress/2016/07/07/forcing-amazon-linux-ami-compatibility-with-centos-in-ansible/

**Comment by valugi** [comment]
@magicalyak thanks for the pointers, I will test them.

**Comment by alessfg** [comment]
Glad to see you might have found a workaround. As far as why NGINX Open Source is not supported on Amazon Linux, the best answer I can give you is that NGINX Open Source, is, well, Open Source, while Amazon Linux is not. NGINX Open Source has a history of carefully avoiding endorsement or support for commercial standards/platforms, and as such, supporting Amazon Linux would not feel quite right nor hold to NGINX's Open Source values. With NGINX Plus, that's not really the case anymore.

**Comment by valugi** [comment]
What!? Nginx open source is available on Mac and Windows XP... which are, well, how should I say it... not open source?
Better come with another excuse.
https://nginx.org/en/#tested_os_and_platforms

**Comment by magicalyak** [comment]
@valugi this was just added in https://github.com/nginxinc/ansible-role-nginx/pull/233
which allows you to install OSS from source and should work with Amazon Linux if you'd like to try.

**Comment by alessfg** [comment]
We've added the option to build from source in #233 -- hopefully that'll work for your use case @valugi  😄

**Comment by alessfg** [comment]
Closing this for the time being. The install from source option should have taken care of this issue (and sadly there's not much more we can do our end if it hasn't).
