### ISSUE TITLE
Cannot install njs module if nginx_version is specified

### ISSUE THREAD

**Issue by djbrogan** [nginxinc/ansible-role-nginx#344]
Without severe coercion, you cannot install a specific version of NGINX Open Source (var nginx_version) with the NJS module.

The root cause appears to be that the NJS module for NGINX is the only module whose versioning differs somewhat, because it is based on a 3rd party library.

| Package | Version |
|---|---|
| nginx | 1.19.4-1~bionic |
| nginx-module-geoip | 1.19.4-1~bionic |
| nginx-module-image-filter | 1.19.4-1~bionic |
| nginx-module-njs | 1.19.4+0.4.4-1~bionic |
| nginx-module-perl | 1.19.4-1~bionic |
| nginx-module-xslt | 1.19.4-1~bionic |

To reproduce via vars passed to the role should be very simple:

```
nginx_enable: yes
nginx_modules:
- njs
nginx_version: =1.19.4-1~bionic
```

**Comment by alessfg** [comment]
Good catch! I think I can have a simple fix in place within the day.

**Comment by alessfg** [comment]
As it turns out, the simple fix I had in mind does not result in a very good UX. I've been doing some further R&D and I think the best solution (for both UX and backwards compatibility reasons) is to add support for an additional module data structure. So in addition to simply specifying a module via
```
- njs
```
You can also use a structure such as
```
- name: njs
  version: =1.19.4+0.4.4-1~bionic
  state: present
```
