### ISSUE TITLE
NGINX config check fails when installing NGINX from a RHEL repository and IPv6 is disabled

### ISSUE THREAD

**Issue by pugnacity** [nginxinc/ansible-role-nginx#410]
### Describe the bug
Installation of nginx fails when IPv6 is disabled

### To reproduce
1. Install System with IPv6 disabled
2. Run basic role

### Expected behavior
nginx reports the errors but continues with the playbook, because the configuration happens in nginx_config

### Your environment:
-   Version of the NGINX Collection 0.3.0
-   Version of Ansible: 2.9.20
-   Target deployment platform: RHEL 8.2

### Additional context
```
RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Check NGINX] ******************************************************************************************************************************************
Tuesday 25 May 2021  13:31:14 +0200 (0:00:00.023)       0:01:01.320 *********** 
fatal: [vlt00162]: FAILED! => {"changed": false, "cmd": ["nginx", "-t"], "delta": "0:00:00.109253", "end": "2021-05-25 13:31:14.955203", "msg": "non-zero return code", "rc": 1, "start": "2021-05-25 13:31:14.845950", "stderr": "nginx: the configuration file /etc/nginx/nginx.conf syntax is ok\nnginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)\nnginx: configuration file /etc/nginx/nginx.conf test failed", "stderr_lines": ["nginx: the configuration file /etc/nginx/nginx.conf syntax is ok", "nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)", "nginx: configuration file /etc/nginx/nginx.conf test failed"], "stdout": "", "stdout_lines": []}
...ignoring

RUNNING HANDLER [nginxinc.nginx_core.nginx : (Handler) Print NGINX error if syntax check fails] **************************************************************************************************************
Tuesday 25 May 2021  13:31:14 +0200 (0:00:00.408)       0:01:01.729 *********** 
fatal: [vlt00162]: FAILED! => {
    "config_check.stderr_lines": [
        "nginx: the configuration file /etc/nginx/nginx.conf syntax is ok",
        "nginx: [emerg] socket() [::]:80 failed (97: Address family not supported by protocol)",
        "nginx: configuration file /etc/nginx/nginx.conf test failed"
    ],
    "failed_when_result": true
}
```

**Comment by alessfg** [comment]
Does your RHEL system have `ipv6` enabled before using the role/collection? And can you share your deployment playbook? I'm trying to replicate your error but I am having difficulty doing so. NGINX should not produce an invalid configuration on a fresh install. That being said I do not disagree with your expected behavior reasoning, but I would like to dig a bit deeper into what might be causing your NGINX config being misconfigured.

**Comment by pugnacity** [comment]
IPv6 was disabled during installation.
Okay the error happens only, when using the package from the Red Hat respository. Thank you for the hint.

**Comment by alessfg** [comment]
Ah! Looks like Red Hat has tweaked the default config to use `ipv6` by default. I'll chat internally to see if we want to change the current config check behavior to a warning instead of leaving it as an error, although given the context we might want to keep it as is to proactively alert users that NGINX might not be getting properly installed.

**Comment by alessfg** [comment]
In the end we are going to keep the current functionality as is. I've changed the issue title to make it a bit more descriptive and easy to search in case someone runs into a similar issue in the future 😄
