### ISSUE TITLE
Certificate verification error in CentOS 7 

### ISSUE THREAD

**Issue by ssttehrani** [nginxinc/ansible-role-nginx#449]
### Describe the bug

Due to LetsEncrypt root certificate expiration on September 30, 2021, the following error occurs in `(Amazon Linux/CentOS/Oracle Linux/RHEL/SLES) Add NGINX signing key` task for CentOS 7.

`fatal: [centos-7]: FAILED! => {"changed": false, "msg": "failed to fetch key at https://nginx.org/keys/nginx_signing.key , error was: Request failed: <urlopen error [SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed (_ssl.c:618)>"}`

### To reproduce

1. Run molecule test with `(Amazon Linux/CentOS/Oracle Linux/RHEL/SLES) Add NGINX signing key` task triggered.

### Expected behavior

The task should fetch signing key without problem.

### Your environment

- Version of the NGINX role or specific commit: 0.21.1
- Version of Ansible: core 2.11.5
- Version of Jinja2: 3.0.1
- Target deployment platform: CentOS 7

**Comment by alessfg** [comment]
There is a bit more to discuss in so far as this specific issue goes. Namely, as you might notice, the role does try to install `ca-certificates` in CentOS, but since it's already installed, the task does nothing and moves along. The issue you found can be fixed by updating `ca-certificates` but since that is a key package for the role to work correctly, this should, perhaps, be handled by the role, instead of the Molecule Dockerfile or a playbook `pre_task` that updates packages.

There's three ways to address this then:
a) Add a task to update all packages to their latest versions (make it optional by using a variable such as `nginx_update_dependencies`).
b) Add a `pre_task` to the Molecule `converge.yml` playbook -- or add a tasks to the Molecule `prepare.yml` playbook.
c) Update the Molecule Dockerfile.

Out of these three, I think a) might be my preferred solution? b) and c) work, but they do not fix the core issue raised by this task (outdated dependencies are not updated by Ansible by default).

**Comment by alessfg** [comment]
I ended up implementing a fix in #452 😄
