### ISSUE TITLE
Can't deploy Nginx role on a RHEL machine behind a proxy

### ISSUE THREAD

**Issue by gabrielnoguerales** [nginxinc/ansible-role-nginx#542]
### Describe the bug

The install of Nginx fails as it can't reach the url because it is not configured to use the proxy

I have the proxy set on both yum config and env variables http_proxy and https_proxy

Playbook fail:
<img width="1009" alt="Playbook_error" src="https://user-images.githubusercontent.com/42550410/185872595-e3817548-f5f9-422c-a226-6e85ca0ea2e6.png">

Proxy config on yum

<img width="768" alt="yum config" src="https://user-images.githubusercontent.com/42550410/185873249-1011b9fb-ba2e-4d09-af16-c1dcc852508e.png">

Proxy config on env
<img width="768" alt="env proxy" src="https://user-images.githubusercontent.com/42550410/185873313-0b80873a-fe48-4de2-a617-0148219c1eed.png">

### To reproduce

1. Deploy NGINX role using playbook.yml using a prox
2. View output/logs/configuration on '...'
3. See error

### Your environment

- Version of the NGINX role or specific commit
0.23.1

- Version of Ansible
<img width="768" alt="ansible-version" src="https://user-images.githubusercontent.com/42550410/185873642-6b781238-4f2b-40fa-ab09-d11e0c5021dc.png">

- Target deployment platform
RHEL 7

**Comment by alessfg** [comment]
Heya!

So, the tl;dr is that for security purposes, having an RPM signing key around tends to be a pretty good idea. The task that is failing means that the role is indeed not capable of accessing the .org endpoint to pull the signing key. The only real way to change the endpoint is to use the `nginx_signing_key` variable, but you would need to host the RPM signing key in an endpoint of your choice.

That being said, if you are running into issues pulling the signing key, you will most likely run into issues pulling the NGINX OSS RHEL package too since it is hosted on the same .org endpoint. Might I suggest you try to figure out how to tweak your proxy environment to open up access to the .org environment in question?

**Comment by gabrielnoguerales** [comment]
Hello,

The problem is that is not using the proxy set on HTTP_PROXY and HTTPS_PROXY on env. If I wget or curl the url it works.

**Comment by alessfg** [comment]
Have you tried setting the environment variables as a pre_task before the role runs? This doc actually references the `HTTP_PROXY` environment variable so it might set you in the right path https://docs.ansible.com/ansible/latest/user_guide/playbooks_environment.html

**Comment by alessfg** [comment]
Closing this for the time being. The link in the previous comment is by all accounts the best native solution.
